import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Layout/navbar";
import Footer from "@/components/Layout/footer";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import 'animate.css';
import { Toaster } from "react-hot-toast";
import ProvidersContainer from "@/components/StoreProvider/ProvidersContainer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProvidersContainer>
          <Navbar />
          {children}
          <Footer />
          <Toaster />
        </ProvidersContainer>
        <SpeedInsights />

        {/* <WishlistContextProvider>
          <CartContextProvider>
            <Navbar />
            {children}
            <Footer />
            <Toaster />
          </CartContextProvider>
        </WishlistContextProvider> */}

      </body>
    </html>
  );
}
